# Mobile menu / footer menu - social links collapse here on mobile
[[main]]
  name = "linkedin"
  url = "https://linkedin.com/in/pbachas/"
  pre = "linkedin"
  weight = 10

[[main]]
  name = "email"
  url = "mailto:career-pgbd@pm.me"
  pre = "email"
  weight = 20

[[main]]
  name = "github"
  url = "https://github.com/hihipy"
  pre = "github"
  weight = 30
