title: "Philip Gregory Bachas-Daunert"
description: "Business Analyst"
remote_theme: just-the-docs/just-the-docs

# Enable SCSS customization
sass:
  sass_dir: _sass

# Site configurations
color_scheme: custom

# Navigation links
aux_links:
  "GitHub Profile":
    - "//github.com/hihipy"
  "LinkedIn":
    - "//linkedin.com/in/pbachas"
  "Bitly Link-in-bio":
    - "//bit.ly/m/pgbd"

aux_links_new_tab: true

# Footer content
footer_content: "© 2024 Philip Gregory Bachas-Daunert"