title: "Philip Gregory Bachas-Daunert"
description: "Business Analyst"
remote_theme: just-the-docs/just-the-docs

# Enable SCSS customization
sass:
  sass_dir: _sass

# Site configurations
color_scheme: custom
logo: assets/images/qr-code.png # Use QR code as the logo

# Navigation settings
just_the_docs:
  collapse_section: true # Enable collapsible menu
  default_layout: "default" # Use the default layout
  aux_links:
    "GitHub Profile": //github.com/hihipy
    "LinkedIn": //linkedin.com/in/pbachas
    "Bitly Link-in-bio": //bit.ly/m/pgbd
  aux_links_new_tab: true

# Footer content
footer_content: "© 2024 Philip Gregory Bachas-Daunert"

# Reorder navigation menu
nav_order: # Ensures correct order for navigation items
  - Home
  - Work Experience
  - Education
  - Skills
  - Key Projects